language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-support
    - extra-android-m2repository

jdk: oraclejdk8

before_script:
    - chmod +x gradlew

script:
    ./gradlew build
